import sys
sys.path.insert(0,'../../../SV-Sim/build/')
import libsvsim_py_cpu_sin as svsim

if (len(sys.argv) != 2):
	print('$python circuit.py n_qubits')
	exit()

sim = svsim.Simulation(int(sys.argv[1]))

# Error correction: distance-three 5-qubit code, from the paper "Benchmarking gate-based quantum computers" by K. Michielsen et al.
sim.append(sim.H(0))
sim.append(sim.H(1))
sim.append(sim.ID(2))
sim.append(sim.H(3))
sim.append(sim.H(4))
sim.append(sim.CX(1, 2))
sim.append(sim.H(1))
sim.append(sim.H(2))
sim.append(sim.CX(1, 2))
sim.append(sim.H(1))
sim.append(sim.H(2))
sim.append(sim.CX(1, 2))
sim.append(sim.CX(4, 2))
sim.append(sim.CX(1, 2))
sim.append(sim.H(1))
sim.append(sim.H(2))
sim.append(sim.CX(1, 2))
sim.append(sim.H(1))
sim.append(sim.H(2))
sim.append(sim.CX(1, 2))
sim.append(sim.SDG(4))
sim.append(sim.CX(4, 2))
sim.append(sim.H(2))
sim.append(sim.CX(4, 2))
sim.append(sim.H(2))
sim.append(sim.CX(0, 2))
sim.append(sim.H(0))
sim.append(sim.H(2))
sim.append(sim.CX(0, 2))
sim.append(sim.H(0))
sim.append(sim.H(2))
sim.append(sim.CX(0, 2))
sim.append(sim.CX(3, 2))
sim.append(sim.CX(0, 2))
sim.append(sim.H(0))
sim.append(sim.H(2))
sim.append(sim.CX(0, 2))
sim.append(sim.H(0))
sim.append(sim.H(2))
sim.append(sim.CX(0, 2))
sim.append(sim.CX(1, 2))
sim.append(sim.H(1))
sim.append(sim.H(2))
sim.append(sim.CX(1, 2))
sim.append(sim.H(1))
sim.append(sim.H(2))
sim.append(sim.CX(1, 2))
sim.append(sim.CX(3, 2))
sim.append(sim.CX(1, 2))
sim.append(sim.H(1))
sim.append(sim.H(2))
sim.append(sim.CX(1, 2))
sim.append(sim.H(1))
sim.append(sim.H(2))
sim.append(sim.CX(1, 2))
sim.append(sim.CX(3, 2))
sim.append(sim.CX(0, 2))
sim.append(sim.H(3))
sim.append(sim.H(4))
sim.append(sim.CX(3, 2))
sim.append(sim.H(2))
sim.append(sim.H(3))
sim.append(sim.CX(3, 2))
sim.append(sim.H(2))
sim.append(sim.H(3))
sim.append(sim.CX(3, 2))
sim.append(sim.CX(0, 2))
sim.append(sim.CX(3, 2))
sim.append(sim.H(2))
sim.append(sim.H(3))
sim.append(sim.CX(3, 2))
sim.append(sim.H(2))
sim.append(sim.H(3))
sim.append(sim.CX(3, 2))
sim.append(sim.CX(4, 2))
sim.append(sim.H(2))
sim.append(sim.H(4))
sim.append(sim.CX(4, 2))
sim.append(sim.H(2))
sim.append(sim.H(4))
sim.append(sim.CX(4, 2))
sim.append(sim.CX(0, 2))
sim.append(sim.CX(4, 2))
sim.append(sim.H(2))
sim.append(sim.H(4))
sim.append(sim.CX(4, 2))
sim.append(sim.H(2))
sim.append(sim.H(4))
sim.append(sim.CX(4, 2))
sim.append(sim.CX(1, 2))
sim.append(sim.H(2))
sim.append(sim.CX(1, 2))
sim.append(sim.H(1))
sim.append(sim.CX(4, 2))
sim.append(sim.CX(0, 1))
sim.append(sim.H(2))
sim.append(sim.H(4))
sim.append(sim.H(1))
sim.append(sim.CX(4, 2))
sim.append(sim.H(2))
sim.append(sim.H(4))
sim.append(sim.CX(4, 2))
sim.append(sim.CX(1, 2))
sim.append(sim.CX(4, 2))
sim.append(sim.H(2))
sim.append(sim.H(4))
sim.append(sim.CX(4, 2))
sim.append(sim.H(2))
sim.append(sim.H(4))
sim.append(sim.CX(4, 2))
sim.append(sim.SDG(1))
sim.append(sim.H(2))
sim.append(sim.H(3))
sim.append(sim.H(4))

sim.upload()
sim.run()
sim.measure(10)
